default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.6.0"
    hooks:
    - id: biome-check
      additional_dependencies: ["@biomejs/biome@1.8.3"]
    - id: biome-format
      additional_dependencies: ["@biomejs/biome@1.8.3"]
